import { Inter } from "next/font/google";
import "./globals.css";
//components
import Navbar from "./components/Navbar";
import ReduxProvider from "./reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <main className="max-container">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
